# Use Python image
FROM python:3.9-slim

# Set the working directory
WORKDIR /app

# Copy your files into the app
COPY . .

# Install the tools from your requirements.txt
RUN pip install -r requirements.txt

# Tell the system to run your streamlit app
EXPOSE 8501
CMD ["streamlit", "run", "app.py", "--server.port=8501", "--server.address=0.0.0.0"]